### ISSUE TITLE
Getting Started wiki page access

### ISSUE THREAD

**Issue by brett-diamondage** [Sage-Bionetworks-Workflows/aws-workflows-nextflow-infra#191]
I am not a Sage employee. Is there any way to gain access to the Getting Started documentation wiki page?

[Getting Started with Nextflow and Tower](https://sagebionetworks.jira.com/wiki/spaces/WF/pages/2191556616/Getting+Started+with+Nextflow+and+Tower#Getting-Help)

**Comment by thomasyu888** [comment]
Hello @brett-diamondage ,

Thanks for your interest, much of whats written in our confluence docs are for our internal usage of Tower pertaining to how we have set up Tower along with our internal SOPs.  I'd have to check if I can make them public, but here are some resources that Seqera provides:

* Tower: https://help.tower.nf/23.1/
* Nextflow: https://www.nextflow.io/

May I ask if you are trying to host Nextflow Tower infrastructure, or learn Nextflow, or neither?  Maybe we can point you in the right direction to help you.
